app/urls.py
from page.views import IndexView
from django import urls
from page import *
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('', IndexView.as_view(), name='index')
    # path('index/', include('app.urls'))
]

page/urls.py
from page import views
from page.views import *
from django.urls import path


app_name = 'myapp'

urlpatterns = [
    path('about', About.as_view(), name='about'),
    path('contact', Contact.as_view(), name='contact'),
    path('product', Product.as_view(), name='product')

]

page/models.py
from django.db import models

# Create your models here.

page/views.py
from django.views.generic import  TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

class Product(TemplateView):
    template_name = 'products.html'

class Contact(TemplateView):
    template_name = 'contact.html'

class About(TemplateView):
    template_name = 'about.html'

class About(TemplateView):
    template_name = 'about.html'

page/templates/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Altamar - Chiping</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>altamar <em>Chiping</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Inicio
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="#">Nuestros Servicios</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myapp:about' %}">Sobre Nosotros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:contact' %}">Contactanos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <div class="page-heading about-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-15">
            <!-- <div class="text-content">
              <h4>Sobres Nosotros</h4>
              <h2>Nuestra Copa</h2>
            </div> -->
          </div>
        </div>
      </div>
    </div>


    <div class="best-features about-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Nuestra Compañía</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="{% static 'images/feature-image.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Quiénes Somos &amp; Que Hacemos?</h4>
              <p style="text-align: justify;">Somos una empresa dedicada al envio de encomiendas personales y comerciales puerta a puerta
                a la República Dominicana. Nuestros servicios es desde las ciudades de New York, New Jersey, 
                Connecticut, Rhode Island, Pennsylvania. Trabajamos 7 días a la semana para brindarte la mejor 
                opción a la hora de programar tu cita. Enviamos Ectrodomésticos, Carros, Tanques y Cajas. Garantizamos 
                una entrega puntual y cuidadosa de tus envíos.</p>
              <ul class="social-icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div>
      <br>
    </div>
    </div> -->

    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="service-item">
              <div class="icon">
                <i class="fa fa-paper-plane"></i>
              </div>
              <div class="down-content">
                <h4>Nuestra Misión</h4>
                <p style="text-align: justify;">Brindar soluciones logísticas únicas, profecionales y a la medida
                   en el propio Transporte de Carga Internacional y Logística a la República Dominicana. con el fin
                   de satisfacer y apoyar con éxito todas las necesidades de nuestros clientes.</p>
                <a href="#" class="filled-button">Read More</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="service-item">
              <div class="icon">
                <i class="fa solid fa-globe"></i>
              </div>
              <div class="down-content">
                <h4>Nuestro Visión</h4>
                <p style="text-align: justify;">Queremos ser un proveedor líder a nivel Mundial como uno de los principales 
                  transportistas de cargas Internacionales, aportando soluciones, y logísticas profecionales a la medida.</p>
                <a href="#" class="filled-button">Details</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="service-item">
              <div class="icon">
                <i class="fa fa-envelope"></i>
              </div>
              <div class="down-content">
                <h4>Nuestros Valores</h4>
                <ul style="text-align: left">
                  <li>Compromiso.</li>
                  <li>Trabajo en Equipo.</li>
                  <li>Innovación.</li>		
                  <li>Honestidad.</li>
                  <li>Puntualidad.</li>																									
                </ul>
                <a href="#" class="filled-button">Read More</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="happy-clients">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <!-- <h2>Happy Partners</h2> -->
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-clients owl-carousel">
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="1">
              </div>
              
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="2">
              </div>
              
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="3">
              </div>
              
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="4">
              </div>
              
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="5">
              </div>
              
              <div class="client-item">
                <img src="{% static 'images/client-01.png' %}" alt="6">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p>            
                Altamar&copy;  <a rel="nofollow noopener" href="https://www.instagram.com/percysanchez_/" target="_blank">Chipping</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

page/templates/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static%}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Sixteen Clothing HTML Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}"><h2>Altamar <em>Chipping</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Inicio
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="#">Nuestros Servicios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:about' %}">Sobre Nosotros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:contact' %}">Contactos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="banner header-text">
      <div class="owl-banner owl-carousel">
        <div class="banner-item-01">
          <div class="text-content">
            <!-- <h4>Best Offer</h4>
            <h2>New Arrivals On Sale</h2> -->
          </div>
        </div>
        <div class="banner-item-02">
          <div class="text-content">
            <!-- <h4>Flash Deals</h4>
            <h2>Get your best products</h2> -->
          </div>
        </div>
        <div class="banner-item-03">
          <div class="text-content">
            <!-- <h4>Last Minute</h4>
            <h2>Grab last minute deals</h2> -->
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Nuestro Servicio</h2>
              <!-- <a href="products.html">v <i class="fa fa-angle-right"></i></a> -->
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'images/tip7.jpg' %}" alt=""></a>
              <div class="down-content">
                <a href="#"><h4>Compromiso</h4></a>
            
                <p style="text-align: justify;">Hacemos una posterior revisión de tu paquete, ante de ser enviado y ha sí garantizar que es el correcto.</p>
              
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'images/h.png' %}" alt=""></a>
              <div class="down-content">
                <a href="#"><h4>confianza</h4></a>
           
                <p style="text-align: justify;">u paquete estará seguro con nosotros, de forma Marítima o por aire, pero siempre a tiempo.</p>
               
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="product-item">
              <a href="#"><img src="{% static 'images/sec2.jpeg' %}" alt=""></a>
              <div class="down-content">
                <a href="#"><h4>Seguridad</h4></a>
                
                <p style="text-align: justify;">Una vez que el paquete es revisado, procedemos a enviarlo, ha si garantizamos un mejor servicios para veneficio de todo, a todo momento.</p>
               
              </div>
            </div>
          </div>
 
    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Acerca de Altamar Chipping</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Brindamos los mejores Servicios</h4>
              <p style="text-align: justify;"> Su mercancia esta segura con nosotros, protejemos de manera, y garantizamos  la integridad de ellas al momento de ser inviada para ha si generar confianza en cada uno de los usuarios.</p>
              
              <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul>
              <a href="{% url 'myapp:about' %}" class="filled-button">Leer Mas</a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src="{% static 'images/tip8.jpeg' %}" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <!-- &amp; -->
                  <h4>Altamar  <em>Chipping</em></h4>
                  <p style="text-align: justify;">La dirección de entrega puede ser diferente de la dirección de facturación, y se debe especificar.
                    Además, no se envían paquetes sin la confirmación del cliente. De esta manera, usted 
                    estará bien informado acerca de la fecha de entrega, y puede realizar cambios en caso de que no esté 
                    disponible para recibir el paquete en la fecha especificada. Los paquete pueden ser entregado en otra dirección 
                    (por ejemplo, la dirección de trabajo). No entregamos en apartados.</p>
                </div>
                <div class="col-md-4">
                  <a href="#" class="filled-button">Informarte ahora</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>

    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p>
            
                Altamar&copy;  <a rel="nofollow noopener" href="https://www.instagram.com/percysanchez_/" target="_blank">Chipping</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

page/templates/products.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Sixteen Clothing Products</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Altamar <em>Chipping</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Inicio
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myapp:product' %}">Lista de Servicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:about' %}">Quienes Somos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:contact' %}">Contactos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>new arrivals</h4>
              <h2>sixteen products</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Products</li>
                  <li data-filter=".des">Featured</li>
                  <li data-filter=".dev">Flash Deals</li>
                  <li data-filter=".gra">Last Minute</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_01.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$18.25</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (12)</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 all dev">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_02.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$16.75</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (24)</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 all gra">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_03.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$32.50</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (36)</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 all gra">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_04.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$24.60</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (48)</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 all dev">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_05.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$18.75</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (60)</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <a href="#"><img src="assets/images/product_06.jpg" alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>Tittle goes here</h4></a>
                          <h6>$12.50</h6>
                          <p>Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur.</p>
                          <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                          </ul>
                          <span>Reviews (72)</span>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="col-md-12">
            <ul class="pages">
              <li><a href="#">1</a></li>
              <li class="active"><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <p>Copyright &copy; 2020 Sixteen Clothing Co., Ltd.
            
            - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>